name: EdwardPatrickKranz
favicon: null
layout_spectrum: 0.70725
typography_spectrum: 0.7171
title: Edward Patrick Ezju Kranz
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f7e6b0'
    - '#060000'
    - '#848893'
    - '#794144'
    - '#950c0f'
  brandStrength: 1
  lightness: 0.5
  saturation: 0
  rhythmicContrast: 0.5
purpose: []
