name: EdwardPatrickKranz
favicon: null
layout_spectrum: 0.11861
typography_spectrum: 0.7171
title: Edward Patrick Ezju Kranz
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#021420'
    - '#332b40'
    - '#8e6583'
    - '#9baebc'
    - '#295f57'
  brandStrength: 0
  lightness: 0.375
  saturation: 0.375
  rhythmicContrast: 0.5
purpose: []
