typography_spectrum: 0.7171
color:
  brandColors:
    - '#021420'
    - '#332b40'
    - '#8e6583'
    - '#9baebc'
    - '#295f57'
  brandStrength: 0.5
  lightness: 0.375
  saturation: 0.375
  rhythmicContrast: 0.75
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.24138
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: Edward Patrick Kranz
  email: ezju.kranz@gmail.com
name: EdwardPatrickKranz
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Edward Patrick Ezju Kranz
purpose: []
